// File automatically generated from OpenAPI spec.
module stripe.model.invoice_setting_quote_setting;

import vibe.data.serialization : optional;
import vibe.data.json : Json;

import std.typecons : Nullable;


/**
 */
class InvoiceSettingQuoteSetting {
  /**
   * Number of days within which a customer must pay invoices generated by this quote. This value
   * will be `null` for quotes where `collection_method=charge_automatically`.
   */
  @optional
  Nullable!(int) days_until_due;

}
