// File automatically generated from OpenAPI spec.
module stripe.model.payment_method_details_ideal;

import vibe.data.serialization : optional;
import vibe.data.json : Json;

import std.typecons : Nullable;

import stripe.model.mandate : Mandate;
import stripe.model.payment_method : PaymentMethod;

/**
 */
class PaymentMethodDetailsIdeal {
  /**
   * The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `handelsbanken`, `ing`,
   * `knab`, `moneyou`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, or
   * `van_lanschot`.
   */
  @optional
  string bank;

  /**
   * Last four characters of the IBAN.
   */
  @optional
  string iban_last4;

  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  @optional
  Json generated_sepa_debit;

  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  @optional
  Json generated_sepa_debit_mandate;

  /**
   * The Bank Identifier Code of the customer's bank.
   */
  @optional
  string bic;

  /**
   * Owner's verified full name. Values are verified or provided by iDEAL directly
   * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  @optional
  string verified_name;

}
