// File automatically generated from OpenAPI spec.
module stripe.model.payment_method_details_sofort;

import vibe.data.serialization : optional;
import vibe.data.json : Json;

import std.typecons : Nullable;

import stripe.model.mandate : Mandate;
import stripe.model.payment_method : PaymentMethod;

/**
 */
class PaymentMethodDetailsSofort {
  /**
   * Two-letter ISO code representing the country the bank account is located in.
   */
  @optional
  Nullable!(string) country;

  /**
   * Last four characters of the IBAN.
   */
  @optional
  Nullable!(string) iban_last4;

  /**
   * Bank code of bank associated with the bank account.
   */
  @optional
  Nullable!(string) bank_code;

  /**
   * Owner's verified full name. Values are verified or provided by SOFORT directly
   * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  @optional
  Nullable!(string) verified_name;

  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  @optional
  Json generated_sepa_debit;

  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  @optional
  Json generated_sepa_debit_mandate;

  /**
   * Name of the bank associated with the bank account.
   */
  @optional
  Nullable!(string) bank_name;

  /**
   * Bank Identifier Code of the bank associated with the bank account.
   */
  @optional
  Nullable!(string) bic;

  /**
   * Preferred language of the SOFORT authorization page that the customer is redirected to.
   * Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
   */
  @optional
  Nullable!(string) preferred_language;

}
