// File automatically generated from OpenAPI spec.
module stripe.model.setup_attempt_payment_method_details_card_present;

import vibe.data.serialization : optional;
import vibe.data.json : Json;

import std.typecons : Nullable;

import stripe.model.payment_method : PaymentMethod;

/**
 */
class SetupAttemptPaymentMethodDetailsCardPresent {
  /**
   * The ID of the Card PaymentMethod which was generated by this SetupAttempt.
   */
  @optional
  Json generated_card;

}
