// File automatically generated from OpenAPI spec.
module stripe.model.invoice_setting_subscription_schedule_setting;

import vibe.data.serialization : optional;
import vibe.data.json : Json;
import builder : AddBuilder;

import std.typecons : Nullable;


/**
 */
class InvoiceSettingSubscriptionScheduleSetting {
  /**
   * Number of days within which a customer must pay invoices generated by this subscription
   * schedule. This value will be `null` for subscription schedules where
   * `billing=charge_automatically`.
   */
  @optional
  Nullable!(int) days_until_due;

  mixin AddBuilder!(typeof(this));

}
